name: Base Docker build workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            devops-training:latest
            devops-training:v1.0.0
            devops-training:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
