name: terraform-plan
on:
  pull_request:
    branches: [master]
    paths: ["terraform/**", ".github/workflows/terraform-*.yml"]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: tf-${{ github.ref }}
  cancel-in-progress: true
jobs:
  plan:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform/envs/dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: terraform version
      - run: terraform fmt -check -recursive
      - run: terraform init -input=false
      - run: terraform workspace select staging || terraform workspace new staging
      - run: terraform validate
      - run: terraform plan -input=false -no-color
